theme: jekyll-theme-slate
title: Hi, My name is Varun and I work on deep learning pipelines.
description: मेरा नाम वरुण है और मैं डीप लर्नींग पाइप्लाइन्स पे काम करता हूं।  </br>    Mera naam Varun hai aur me Deep Learning pipelines pe kaam karta hun. Meet my friend M.K. Gandhi speaking on my behalf. 
